version: '3.8'
services:
  minetest:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started # does not have service_healthy
    volumes:
      - minetest-data:/config/.minetest
    env_file:
      - .env
    ports:
      - 30000:30000/udp
  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres-data:
  minetest-data:
