---
version: "2.1"
services:
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: minetest
    environment:
      - TZ=Europe/London
    volumes:
      - minetest:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped
volumes:
  minetest: {}